"""add user wecom userid

Revision ID: 53ade4be56be
Revises: 8c2e6a1f4b90
Create Date: 2026-09-14 10:00:49.330596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ade4be56be'
down_revision: Union[str, None] = '8c2e6a1f4b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wecom_userid', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_wecom_userid'), ['wecom_userid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wecom_userid'))
        batch_op.drop_column('wecom_userid')

    # ### end Alembic commands ###
