"""create chat messages

Revision ID: c1801e192118
Revises: fbb858a0862d
Create Date: 2026-09-14 15:53:47.553595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1801e192118'
down_revision: Union[str, None] = 'fbb858a0862d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wecom_message_id', sa.String(length=200), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('content_encrypted', sa.Text(), nullable=True),
    sa.Column('content_masked', sa.Text(), nullable=True),
    sa.Column('media_object_key', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wecom_message_id', name='uq_chat_messages_wecom_message_id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_direction'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_customer_id'))

    op.drop_table('chat_messages')
    # ### end Alembic commands ###
