"""add customer follow up time

Revision ID: de24ef215586
Revises: 
Create Date: 2026-09-10 19:19:06.043147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de24ef215586'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 早期 SQLite 由 create_all 初始化，历史中没有创建 customers 的首条迁移。
    # 新 PostgreSQL 从零启动时才补齐基础表；既有 SQLite 不会再次运行本 revision。
    if 'customers' not in sa.inspect(op.get_bind()).get_table_names():
        op.create_table(
            'customers',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('phone', sa.String(length=30), nullable=False),
            sa.Column('student_name', sa.String(length=50), nullable=True),
            sa.Column('grade', sa.String(length=30), nullable=True),
            sa.Column('interested_subject', sa.String(length=50), nullable=True),
            sa.Column('stage', sa.String(length=30), nullable=False),
            sa.Column('source', sa.String(length=50), nullable=True),
            sa.Column('remark', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )
    op.add_column('customers', sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'next_follow_up_at')
    # ### end Alembic commands ###
