"""create timeline events

Revision ID: fbb858a0862d
Revises: 41952d23cca4
Create Date: 2026-09-14 14:47:28.507328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb858a0862d'
down_revision: Union[str, None] = '41952d23cca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('summary_encrypted', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_operator_id'), ['operator_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_operator_id'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_customer_id'))

    op.drop_table('timeline_events')
    # ### end Alembic commands ###
